server.port=8087
spring.datasource.url=jdbc:mysql://localhost:3306/productstoredb
spring.datasource.username=root
spring.datasource.password =root12#
#spring.datasource.url = jdbc:mysql://springapp.cgilq14is5ep.ap-south-1.rds.amazonaws.com/Fruitstoredb
#spring.datasource.username = admin
#spring.datasource.password = admin12#
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#fruit.app.uploadPath=C:/apache-tomcat-9.0.30-windows-x64/apache-tomcat-9.0.30/webapps/FruitUiClient/assets/image"
#fruit.app.uploadPath="/opt/tomcat/apache-tomcat-9.0.31/webapps/ConfigServer/assets/image"
fruit.app.uploadPath=C:/Angular 4/WorkspaceFruits/Angular/FruitJwtComplete/src/assets/image
fruit.app.variable=denmark